<<mads, fig=TRUE, width=8, height=6>>=
library(Beaty)
data(bsSet)
library(RColorBrewer)
pastelcolors <- brewer.pal(4, "Set1")[2:3]
##DNA.source <- as.character(lrSet$DNA.Source)
DNA.source <- as.character(bsSet$DNA.Source)
cell.lines <- c(grep("CEPH", DNA.source),
		grep("HAN CHINESE", DNA.source),
		grep("JAPANESE", DNA.source),
		grep("Yoruba", DNA.source))
DNA.source[cell.lines] <- "cell line"
which.wga <- grep("WGA", DNA.source)

mads <- split(bsSet$MAD, DNA.source)
nn <- sapply(mads, length)

open(bsSet$MAD)



col <- rep(pastelcolors[1], length(mads))
col[which.wga] <- pastelcolors[2]
par(mfrow=c(1,1), mar=c(8, 4, 2, 2), las=1)
boxplot(mads, col=col, pch=".", xaxt="n", ylab="mad(log R ratio)", ylim=c(0, max(unlist(mads))),
	xlim=c(-0.5, length(mads)))
abline(h=0.3, lty=2)
text(x=seq_along(mads), y=rep(0, length(mads)), labels=nn, cex=0.6, srt=90)
text(-0.25, 0, "N:")
par(las=3)
axis(1, at=seq_along(mads),labels=names(mads), cex.axis=0.8)
legend("topleft", fill=pastelcolors[2:1], legend=c("whole genome amplified", "other"), title="DNA source", bty="n")
@










