setGeneric("addSampleSheet", function(object) standardGeneric("addSampleSheet"))
setGeneric("axis.limits", function(object) standardGeneric("axis.limits"))
setGeneric("biparentalHmm", function(object, ...) standardGeneric("biparentalHmm"))
setGeneric("computeBpiEmission", function(object, ...) standardGeneric("computeBpiEmission"))
setGeneric("gtConfidence", function(object) standardGeneric("gtConfidence"))
setGeneric("inheritance", function(object) standardGeneric("inheritance"))
setGeneric("informative", function(object) standardGeneric("informative"))
setGeneric("mendelian", function(object) standardGeneric("mendelian"))
setGeneric("isBiparental", function(object, ...) standardGeneric("isBiparental"))
setGeneric("callDeletion", function(object, ...) standardGeneric(object))
