setGeneric("addSampleSheet", function(object) standardGeneric("addSampleSheet"))
setGeneric("axis.limits", function(object) standardGeneric("axis.limits"))
setGeneric("biparentalHmm", function(object, ...) standardGeneric("biparentalHmm"))
setGeneric("computeBpiEmission", function(object, ...) standardGeneric("computeBpiEmission"))
setGeneric("gtConfidence", function(object) standardGeneric("gtConfidence"))
setGeneric("inheritance", function(object) standardGeneric("inheritance"))
setGeneric("informative", function(object) standardGeneric("informative"))
setGeneric("mendelian", function(object) standardGeneric("mendelian"))
setGeneric("isBiparental", function(object, ...) standardGeneric("isBiparental"))
##setGeneric("callDeletion", function(object, ...) standardGeneric(object))


setGeneric("logR.M", function(object) standardGeneric("logR.M"))
setGeneric("logR.F", function(object) standardGeneric("logR.F"))
setGeneric("logR.O", function(object) standardGeneric("logR.O"))
setGeneric("baf.M", function(object) standardGeneric("baf.M"))
setGeneric("baf.F", function(object) standardGeneric("baf.F"))
setGeneric("baf.O", function(object) standardGeneric("baf.O"))
setGeneric("mindist", function(object) standardGeneric("mindist"))
setGeneric("family", function(object) standardGeneric("family"))
setGeneric("plot", function(object, ...) standardGeneric("plot"))
